-- Create jawda_patient_details table
CREATE TABLE IF NOT EXISTS {target_schema}.jawda_patient_details (
    mr_no VARCHAR,
    patient_name VARCHAR,
    middle_name VARCHAR,
    last_name VARCHAR,
    dateofbirth DATE,
    expected_dob DATE,
    patient_gender VARCHAR,
    custom_list1_value VARCHAR,
    passport_no VARCHAR,
    custom_field2 VARCHAR,
    PRIMARY KEY (mr_no)
);

-- Create jawda_mrd_observations table
CREATE TABLE IF NOT EXISTS {target_schema}.jawda_mrd_observations (
    charge_id VARCHAR,
    observation_type VARCHAR,
    code VARCHAR,
    value VARCHAR,
    value_type VARCHAR
);


-- Create jawda_mrd_diagnosis table
CREATE TABLE IF NOT EXISTS {target_schema}.jawda_mrd_diagnosis (
    visit_id VARCHAR,
    id VARCHAR,
    description VARCHAR,
    icd_code VARCHAR,
    code_type VARCHAR,
    diag_type VARCHAR
);

-- Create a pivot table for diagnosis data
CREATE TABLE IF NOT EXISTS {target_schema}.mrd_diag_pivot (
    visit_id VARCHAR,
    p1 VARCHAR,
    s1 VARCHAR,
    s2 VARCHAR,
    s3 VARCHAR,
    s4 VARCHAR,
    s5 VARCHAR,
    s6 VARCHAR,
    s7 VARCHAR,
    s8 VARCHAR,
    s9 VARCHAR,
    s10 VARCHAR,
    s11 VARCHAR,
    s12 VARCHAR,
    s13 VARCHAR,
    s14 VARCHAR,
    s15 VARCHAR,
    PRIMARY KEY (visit_id)
);

-- Create a pivot table for observations data
CREATE TABLE IF NOT EXISTS {target_schema}.mrd_observs_pivot (
    charge_id VARCHAR,
    code1 VARCHAR,
    code2 VARCHAR,
    code3 VARCHAR,
    code4 VARCHAR,
    code5 VARCHAR,
    obstype1 VARCHAR,
    obstype2 VARCHAR,
    obstype3 VARCHAR,
    obstype4 VARCHAR,
    obstype5 VARCHAR,
    value1 VARCHAR,
    value2 VARCHAR,
    value3 VARCHAR,
    value4 VARCHAR,
    value5 VARCHAR,
    valuetype1 VARCHAR,
    valuetype2 VARCHAR,
    valuetype3 VARCHAR,
    valuetype4 VARCHAR,
    valuetype5 VARCHAR,
    PRIMARY KEY (charge_id)
);

-- Create jawda_patient_registration table for doctor details updates
CREATE TABLE IF NOT EXISTS {target_schema}.jawda_patient_registration (
    mr_no VARCHAR,
    patient_id VARCHAR,
    reg_date DATE,
    reg_time TIME, 
    doctor VARCHAR,
    dept_name VARCHAR,
    transfer_source VARCHAR,
    transfer_destination VARCHAR,
    PRIMARY KEY (patient_id)
);

-- Create main claim data table
CREATE TABLE IF NOT EXISTS {target_schema}.rcm_claim_data (
    claimid VARCHAR PRIMARY KEY,
    memberid VARCHAR,
    payerid VARCHAR,
    providerid VARCHAR,
    receiverid VARCHAR,
    transactiondate VARCHAR,
    emiratesidnumber VARCHAR,
    gross DOUBLE PRECISION,
    patientshare DOUBLE PRECISION,
    netclaim DOUBLE PRECISION,
    encountertype VARCHAR,
    patientid VARCHAR,
    encounterstart VARCHAR,
    encounterend VARCHAR,
    encounterstarttype VARCHAR,
    encounterendtype VARCHAR,
    activityid VARCHAR,
    activitystart VARCHAR,
    activitytype VARCHAR,
    activitycode VARCHAR,
    activityquantity DOUBLE PRECISION,
    activitynet DOUBLE PRECISION,
    orderingclinician VARCHAR,
    prior_auth_id VARCHAR,
    clinician VARCHAR,
    visit_id VARCHAR,
    charge_id VARCHAR,
    insurance_co_id VARCHAR,
    admitting_dr_id VARCHAR,
    category VARCHAR,
    submission_date TIMESTAMP,
    tpa_id VARCHAR,
    center_id VARCHAR,
    act_description VARCHAR,
    plan_id VARCHAR,
    registration_date TIMESTAMP,
    rate_plan_id VARCHAR,
    insurance_category_id VARCHAR,
    patient_type VARCHAR,
    encounterdiagnosisprincipal VARCHAR,
    partition_key BIGINT,
    patientname VARCHAR,
    patientbirthdate DATE,
    age INTEGER,
    gender VARCHAR,
    nationality VARCHAR,
    passport_no VARCHAR,
    encountertransfersource VARCHAR,
    encountertransferdestination VARCHAR,
    encounterdiagnosissecondary1 VARCHAR,
    encounterdiagnosissecondary2 VARCHAR,
    encounterdiagnosissecondary3 VARCHAR,
    encounterdiagnosissecondary4 VARCHAR,
    encounterdiagnosissecondary5 VARCHAR,
    encounterdiagnosissecondary6 VARCHAR,
    encounterdiagnosissecondary7 VARCHAR,
    encounterdiagnosissecondary8 VARCHAR,
    encounterdiagnosissecondary9 VARCHAR,
    encounterdiagnosissecondary10 VARCHAR,
    encounterdiagnosissecondary11 VARCHAR,
    encounterdiagnosissecondary12 VARCHAR,
    encounterdiagnosissecondary13 VARCHAR,
    encounterdiagnosissecondary14 VARCHAR,
    encounterdiagnosissecondary15 VARCHAR,
    activitydescription VARCHAR,
    activitydate DATE,
    activitynotes VARCHAR,
    activityunitcost NUMERIC,
    obscode1 VARCHAR,
    obstype1 VARCHAR,
    obsvalue1 VARCHAR,
    obsvaluetype1 VARCHAR,
    obscode2 VARCHAR,
    obstype2 VARCHAR,
    obsvalue2 VARCHAR,
    obsvaluetype2 VARCHAR,
    obscode3 VARCHAR,
    obstype3 VARCHAR,
    obsvalue3 VARCHAR,
    obsvaluetype3 VARCHAR,
    obscode4 VARCHAR,
    obstype4 VARCHAR,
    obsvalue4 VARCHAR,
    obsvaluetype4 VARCHAR,
    obscode5 VARCHAR,
    obstype5 VARCHAR,
    obsvalue5 VARCHAR,
    obsvaluetype5 VARCHAR,
    doctorname VARCHAR,
    doctorsdepartment VARCHAR,
    primarydiagnosis VARCHAR,
    secondarydiagnosis VARCHAR,
    centername VARCHAR,
    insurance_plan VARCHAR,
    insurance_plan_type VARCHAR,
    rate_plan VARCHAR,
    insurancecompany VARCHAR,
    tpa_name VARCHAR
); 